
language: objective-c 
osx_image: xcode9.4.1
deploy:
    provider: pages
    github-token: 3919d9275699599b8da913e9d3b661fad6f8506d
    skip-cleanup: true
    keep-history: true
    on:
        branch: master

